# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 07:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('contact_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_bal', models.FloatField(blank=True, default=0, null=True)),
                ('esi_bal', models.FloatField(blank=True, default=0, null=True)),
                ('pension_bal', models.FloatField(blank=True, default=0, null=True)),
                ('pf_bal', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'ESI'), (2, 'PENSION'), (3, 'PF')], default=1)),
                ('transaction_status', models.PositiveSmallIntegerField(choices=[(1, 'SUCCESS'), (2, 'PENDING'), (3, 'CANCELLED')], default=2)),
                ('amount', models.FloatField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gateway.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bank_ac_number', models.CharField(blank=True, max_length=80, null=True)),
                ('bank_ac_holder_name', models.CharField(blank=True, max_length=115, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('is_bank_detail_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
