# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
