# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0002_auto_20190228_0759'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
