# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0002_auto_20190303_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueidentitydetails',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
