# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0003_auto_20190303_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='uniqueidentitydetails',
        ),
        migrations.RemoveField(
            model_name='uniqueidentitydetails',
            name='user',
        ),
    ]
